#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Eddie Huang"
email = "aigagror@gmail.com"

[ui]
pager = ["hunk", "pager"]
diff-formatter = ":git"

[aliases]
l = ["log"]
g = ["git"]
