onboarding = false
[keys]
prefix = "ctrl+space"
focus_pane_left = ["prefix+h"]
focus_pane_down = ["prefix+j"]
focus_pane_up = ["prefix+k"]
focus_pane_right = ["prefix+l"]
new_tab = ["prefix+c", "ctrl+alt+n"]
previous_tab = ["prefix+p", "ctrl+alt+h"]
next_tab = ["prefix+n", "ctrl+alt+l"]
split_vertical = ["prefix+v", "ctrl+alt+d"]
split_horizontal = ["prefix+minus", "ctrl+alt+shift+d"]
zoom = ["prefix+z", "ctrl+alt+z"]
previous_workspace = "ctrl+alt+k"
next_workspace = "ctrl+alt+j"

[theme]
name = "catppuccin"
auto_switch = false

[ui]
agent_panel_sort = "spaces"

[[keys.command]]
key = "ctrl+alt+v"
type = "pane"
command = "vcsui"
description = "run lazygit or jj UI"
